stages:
  - build-ci
  - run-ci
  - build-production

variables:
  CONTAINER_PHP_CI: $CI_REGISTRY_IMAGE/php-ci:$CI_COMMIT_SHA

#################################################################
# Settings for building docker images - for tests and deployments
#################################################################

.docker-in-docker-template: &docker-in-docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build-php-ci:
  <<: *docker-in-docker
  stage: build-ci
  script:
      #  If the build exists for this commit, don't build it again - exit (happily)
    - docker pull $CONTAINER_PHP_CI && exit 0
    - DOCKER_BUILDKIT=1 docker build --progress=plain --pull --target with-composer -t $CONTAINER_PHP_CI -f resources/docker/Dockerfile .
    - docker push $CONTAINER_PHP_CI

build-prod:
  <<: *docker-in-docker
  stage: build-production
  variables:
    CONTAINER_PHP_PROD: $CI_REGISTRY_IMAGE/php:$CI_COMMIT_TAG
    CONTAINER_PHP_PROD_LATEST: $CI_REGISTRY_IMAGE/php:latest
    CONTAINER_FRONTEND_PROD: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_TAG
    CONTAINER_FRONTEND_PROD_LATEST: $CI_REGISTRY_IMAGE/frontend:latest
  script:
    - docker pull $CONTAINER_PHP_CI
    - DOCKER_BUILDKIT=1 docker build --progress=plain --pull --target web-production --cache-from $CONTAINER_PHP_CI -t $CONTAINER_FRONTEND_PROD
        -f resources/docker/Dockerfile .
    - docker push $CONTAINER_FRONTEND_PROD
    - docker tag $CONTAINER_FRONTEND_PROD $CONTAINER_FRONTEND_PROD_LATEST
    - docker push $CONTAINER_FRONTEND_PROD_LATEST
    - DOCKER_BUILDKIT=1 docker build --progress=plain --pull --target php-production -t $CONTAINER_PHP_PROD -f resources/docker/Dockerfile .
    - docker push $CONTAINER_PHP_PROD
    - docker tag $CONTAINER_PHP_PROD $CONTAINER_PHP_PROD_LATEST
    - docker push $CONTAINER_PHP_PROD_LATEST
  only:
    - tags

#################################################################
# Settings for running the tests
#################################################################

phpunit:
  image: $CONTAINER_PHP_CI
  stage: run-ci
  before_script:
    - composer install --no-progress --no-suggest -n
  script:
    - ./vendor/bin/phpunit
  artifacts:
    when: on_failure
    paths:
      - storage/logs/
    expire_in: 1 week

phpcs:
  image: $CONTAINER_PHP_CI
  stage: run-ci
  script:
    - $COMPOSER_HOME/vendor/bin/phpcs
