version: '2'
services:
  node:
    container_name: stardew-helpers-node-dev
    build:
      context: .
      dockerfile: resources/docker/Dockerfile
      target: node
    image: stardew-node
    volumes:
      - .:/code
    tmpfs:
      - /opt/home
    environment:
      HOME: '/opt/home'
    working_dir: /code
    user: "${UID}:${GID}"
