version: '2'
services:
  node:
    container_name: stardew-helpers-node-dev
    image: node:10
    volumes:
      - .:/code
    tmpfs:
      - /opt/home
    environment:
      HOME: '/opt/home'
    working_dir: /code
    user: "${UID}:${GID}"
