version: '2.4'

services:
  app:
    container_name: stardew-app
    image: registry.gitlab.com/rickselby-hosted-websites/stardew-helpers/php:latest
    restart: always
    tmpfs:
      - /code/storage/framework/views
    environment:
      CONTAINER_ROLE: app
      APP_URL: https://stardew.djomp.co.uk
      APP_KEY: base64:JIHbDuraVKZHqOLhAR9HBhdvRI9EIq1v8B81BlYlBgY=
      MAP_GRID: 16
      MAP_SCALE: 1
      MAP_SIZE: 400
    networks:
      - stardew-helpers
  web:
    container_name: stardew-web
    image: registry.gitlab.com/rickselby-hosted-websites/stardew-helpers/frontend:latest
    restart: always
    environment:
      VIRTUAL_HOST: stardew.djomp.co.uk
    depends_on:
      - app
    networks:
      - stardew-helpers

networks:
  stardew-helpers:
    name: stardew-helpers
