version: '2.4'

services:
  app:
    container_name: stardew-app
    image: $CONTAINER_PHP_PROD
    restart: always
    tmpfs:
      - /code/storage/framework/views
    environment:
      APP_URL: https://stardew.djomp.co.uk
      APP_KEY: base64:JIHbDuraVKZHqOLhAR9HBhdvRI9EIq1v8B81BlYlBgY=
  web:
    container_name: stardew-web
    image: $CONTAINER_FRONTEND_PROD
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - app

networks:
  default:
    external:
      name: stardew-helpers
